kind: pipeline
name: Python linting

steps:
- name: pylint
  image: python:3.7-stretch
  commands:
  - pip install pylint
  - pip install -r requirements.txt
  - pylint project_amber
  when:
    branch:
      exclude:
      - master
- name: push to registry
  image: plugins/docker
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    repo: registry.git.tdem.in/amber
    registry: registry.git.tdem.in
    auto_tag: true
    dockerfile: Dockerfile
  when:
    branch:
    - master
    event:
    - push
    - tag
