kind: pipeline
name: Python linting

steps:
- name: pylint
  image: python:3.7-stretch
  commands:
  - pip install pylint
  - pip install -r requirements.txt
  - pylint --rcfile .pylintrc project_amber project_amber/handlers project_amber/helpers project_amber/models
  when:
    branch:
      exclude:
      - master
- name: push to registry
  image: plugins/docker
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    repo: registry.git.tdem.in/amber
    registry: registry.git.tdem.in
    dockerfile: Dockerfile
    tags:
      - ${DRONE_TAG}
      - latest
  when:
    branch:
    - master
    event:
    - push
    - tag
