version: "3"

volumes:
  postgres:

services:
  amber:
    build: .
    restart: always
    # You'll likely need to add other drivers, like mysql-connector-python, to
    # connect to databases other than the default SQLite and PostgreSQL. See:
    # https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls
    environment:
      - AMBER_DATABASE=postgres://amber:CHANGEME@database:5432/amber
      - AMBER_LOGLEVEL=2
      - AMBER_ALLOW_SIGNUP=0
      - UWSGI_PORT=8080
      - UWSGI_PROCESSES=1
      - UWSGI_THREADS=2
    depends_on:
      - database
  database:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_DB=amber
      - POSTGRES_USER=amber
      - POSTGRES_PASSWORD=CHANGEME
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    image: nginx:1.16-alpine
    ports:
      - 80:80
    depends_on:
      - amber
    volumes:
      - ./doc/nginx.conf.example:/etc/nginx/conf.d/default.conf:ro
